"""
OrchestratorAgent — UC1 Entry Point
Chains: DataCollector → Calculator → Scoring → Analyst → TrackRecord
"""

from datetime import datetime
from app.agents.data_collector import collect
from app.agents.calculator import calculate
from app.agents.scoring import score
from app.agents.analyst import analyze


def _save_to_db(ticker: str, result: dict, user_id: str = None):
    try:
        from app.db import supabase
        if not supabase or not user_id:
            return None

        synthesis = result.get("synthesis", {})
        score_data = result.get("score", {})

        record = {
            "user_id": user_id,
            "ticker": ticker,
            "action": synthesis.get("decision", "Gray Zone"),
            "reasoning": synthesis.get("summary", ""),
            "ai_score": score_data.get("total_score"),
            "ai_rating": score_data.get("rating"),
            "price_at_decision": result.get("price", {}).get("current"),
        }

        resp = supabase.table("ai_decisions").insert(record).execute()
        return resp.data[0]["id"] if resp.data else None
    except Exception:
        return None


def analyze_stock(ticker: str, user_id: str = None, save: bool = True) -> dict:
    """
    UC1 full pipeline. Returns structured analysis result.
    """
    ticker = ticker.upper().strip()

    # Step 1: Collect raw data
    raw_data = collect(ticker)
    if "error" in raw_data:
        return {"error": raw_data["error"], "ticker": ticker}

    # Step 2: Calculate financial metrics
    calc_result = calculate(raw_data)
    if "error" in calc_result:
        return {"error": calc_result["error"], "ticker": ticker}

    # Step 3: Score (deterministic)
    score_result = score(calc_result, raw_data)

    # Step 4: LLM analysis (4 Masters + synthesis)
    analyst_result = analyze(ticker, raw_data, calc_result, score_result)

    # Assemble full_report_markdown
    synthesis = analyst_result.get("synthesis", {})
    md_report = f"## {ticker} — {synthesis.get('decision', 'N/A')}\n\n"
    md_report += f"**Thesis:** {synthesis.get('thesis', '')}\n\n"
    for key, pers in analyst_result.get("perspectives", {}).items():
        name = pers.get("name", key.capitalize())
        stars = pers.get("stars", 3)
        analysis = pers.get("analysis", "")
        if not analysis and "essence" in pers:
            analysis = pers.get("essence", "")
        md_report += f"### {name} ({stars} Stars)\n{analysis}\n\n"
    md_report += f"### Final Summary\n{synthesis.get('summary', '')}"

    # Extract verdicts
    perspectives_out = {}
    for key, pers in analyst_result.get("perspectives", {}).items():
        verdict = pers.get("analysis", "")
        if len(verdict) > 100:
            verdict = verdict[:97] + "..."
        if not verdict:
            verdict = pers.get("essence", "Analysis unavailable")
        
        perspectives_out[key] = {
            "stars": pers.get("stars", 3),
            "verdict": verdict,
            "full_data": pers  # Keep the full data for the frontend just in case
        }

    # Format score_breakdown
    breakdown_raw = score_result.get("breakdown", {})
    
    # Format scenarios
    scenarios_raw = synthesis.get("scenarios", {})
    scenarios_out = {
        "bull": scenarios_raw.get("bull", {}).get("price", 0),
        "base": scenarios_raw.get("base", {}).get("price", 0),
        "bear": scenarios_raw.get("bear", {}).get("price", 0),
    }

    # Assemble final output matching the requested schema exactly
    result = {
        "ticker": ticker,
        "company_name": raw_data.get("company", {}).get("name", ticker),
        "price": raw_data.get("price", {}).get("current", 0),
        "score": score_result.get("total_score", 0),
        "rating": score_result.get("rating", "N/A"),
        "one_liner": synthesis.get("thesis", "Analysis generated by 4 Masters Framework."),
        
        "perspectives": perspectives_out,
        "composite_stars": analyst_result.get("composite_stars", 3),
        
        "score_breakdown": {
            "fundamentals": { "score": breakdown_raw.get("quality", 0), "details": "Derived from Quality and Growth." },
            "technical":    { "score": breakdown_raw.get("technical", 0), "details": "Derived from moving averages and momentum." },
            "sentiment":    { "score": breakdown_raw.get("sentiment", 0), "details": "Derived from news and analysts." },
            "value":        { "score": breakdown_raw.get("value", 0), "details": "Derived from DCF and Multiples." }
        },
        "valuation": {
            "dcf_fair_value": calc_result.get("dcf", {}).get("fair_value", 0),
            "scenarios": scenarios_out
        },
        
        "decision": synthesis.get("decision", "Gray Zone"),
        "action": synthesis.get("action", "Hold"),
        "bull_case": synthesis.get("bull_case", []),
        "bear_case": synthesis.get("bear_case", []),
        "catalysts": raw_data.get("company", {}).get("catalysts", []),
        
        "full_report_markdown": md_report,
        
        # Legacy/Extra fields appended to preserve any backward compatibility if needed internally
        "_analyzed_at": datetime.utcnow().isoformat(),
        "_raw_synthesis": synthesis,
    }

    # Step 5: Save to DB (TrackRecord)
    if save and user_id:
        decision_id = _save_to_db(ticker, {"synthesis": synthesis, "score": score_result, "price": raw_data.get("price")}, user_id)
        result["decision_id"] = decision_id

    return result
